# Generated by Django 4.2.6 on 2023-10-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_category_remove_product_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='2kg', max_length=50, verbose_name='Unit'),
            preserve_default=False,
        ),
    ]
