# Generated by Django 4.2.6 on 2023-11-04 08:20

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_rank',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['search_vector'], name='Products_pr_search__085b1a_idx'),
        ),
    ]
