# Generated by Django 4.2.6 on 2023-11-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_product_search_rank_product_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='Products_pr_search__085b1a_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='Products_pr_title_6f06ce_idx'),
        ),
    ]
