# Generated by Django 4.2.6 on 2023-11-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_rating_product_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='ratings',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=50, verbose_name='Ratings'),
        ),
    ]
