# Generated by Django 4.2.6 on 2024-01-15 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0008_alter_rating_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Percentage Discount')),
                ('start_time', models.DateTimeField(verbose_name='Discount Start Time')),
                ('end_time', models.DateTimeField(verbose_name='Discount End TimeS')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'ProductDiscount',
                'verbose_name_plural': 'ProductDiscounts',
            },
        ),
    ]
