# Generated by Django 4.2.6 on 2024-01-15 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_productdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percentage_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='Products.productdiscount', verbose_name=''),
        ),
    ]
