# Generated by Django 4.2.6 on 2024-01-19 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percentage_discount',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percentage_discount', to='Products.productdiscount', verbose_name='Discount (%)'),
        ),
    ]
